version: "3"

services:
    mongodb:
        image: mongo:3
        volumes:
            - ./runtime/mongo/data:/data/db

    elasticsearch:
        image: elasticsearch-for-graylog
        build:
            context: elasticsearch/
            dockerfile: Dockerfile
            args:
                - ELK_VERSION=6.6.1
        restart: always
        environment:
            - cluster.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - ./runtime/elasticsearch/data:/usr/share/elasticsearch/data

    graylog:
        image: graylog/graylog:3.0
        container_name: container-graylog
        hostname: graylog
        volumes:
            - ./runtime/graylog/journal:/usr/share/graylog/data/journal
        environment:
            - GRAYLOG_HTTP_EXTERNAL_URI=http://prism.goblin.com:9000/
            # CHANGE ME (must be at least 16 characters)!
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
            - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - mongodb
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp
            # fileBeats TCP
            - 5044:5044
            # kafka 9092
            - 9092:9092

networks:
    default:
        external:
            name: jetea_net
